<!DOCTYPE html>
<html>
<head>
    <title>Bills Report</title>
    <style>
        /* Same base styles as cash_flow.blade.php */
    </style>
    @include('partials.report-print-styles')
</head>
<body>
<div class="header">
    <h1>Bills Report</h1>
    <p>{{ $data->start_date }} to {{ $data->end_date }}</p>
    <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
</div>

@foreach($data->grouped_data as $groupName => $group)
    <h3>{{ $groupName }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Control #</th>
            <th>Date</th>
            <th>Customer</th>
            <th class="text-right">Amount</th>
            <th class="text-right">Paid</th>
            <th>Status</th>
            <th>Due Date</th>
        </tr>
        </thead>
        <tbody>
        @foreach($group->bills as $bill)
            <tr>
                <td>{{ $bill->control_number }}</td>
                <td>{{ $bill->created_at->format('Y-m-d') }}</td>
                <td>{{ $bill->customer_name }}</td>
                <td class="text-right">Tsh {{ number_format($bill->amount, 2) }}</td>
                <td class="text-right">Tsh {{ number_format($bill->paid_amount, 2) }}</td>
                <td>{{ ucfirst($bill->status) }}</td>
                <td>{{ $bill->expires_at->format('Y-m-d') }}</td>
            </tr>
        @endforeach
        <tr>
            <td colspan="3"><strong>Total</strong></td>
            <td class="text-right"><strong>Tsh {{ number_format($group->total_amount, 2) }}</strong></td>
            <td class="text-right"><strong>Tsh {{ number_format($group->total_paid, 2) }}</strong></td>
            <td colspan="2"></td>
        </tr>
        </tbody>
    </table>
@endforeach

<div class="footer">
    <p>Generated by {{ auth()->user()?->username ?? config('app.name') }} on {{ now()->format('Y-m-d H:i:s') }}</p>
</div>
</body>
</html>
