<!DOCTYPE html>
<html>
<head>
    <title>Cash Flow Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 18px; }
        .header p { margin: 5px 0 0; color: #666; }
        .summary { margin-bottom: 20px; }
        .summary-card { border: 1px solid #ddd; padding: 10px; margin-bottom: 10px; }
        .summary-card h3 { margin: 0 0 5px; font-size: 14px; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f5f5f5; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .page-break { page-break-after: always; }
        .footer { margin-top: 20px; font-size: 10px; color: #666; text-align: center; }
    </style>
    @include('partials.report-print-styles')
</head>
<body>
<div class="header">
    <h1>Cash Flow Report</h1>
    <p>{{ $data->summary->start_date }} to {{ $data->summary->end_date }}</p>
    <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
</div>

<div class="summary">
    <div class="row">
        <div class="summary-card">
            <h3>Summary</h3>
            <p>Total Income: Tsh {{ number_format($data->summary->total_income, 2) }}</p>
            <p>Total Expenses: Tsh {{ number_format($data->summary->total_expenses, 2) }}</p>
            <p>Net Cash Flow: Tsh {{ number_format($data->summary->net_cash_flow, 2) }}</p>
        </div>
    </div>
</div>

<h3>Transactions</h3>
<table class="table">
    <thead>
    <tr>
        <th>Period</th>
        <th class="text-right">Total Amount</th>
        <th class="text-right">Transactions</th>
    </tr>
    </thead>
    <tbody>
    @foreach($data->transactions as $period => $group)
        <tr>
            <td>{{ $period }}</td>
            <td class="text-right">Tsh {{ number_format($group->total_amount, 2) }}</td>
            <td class="text-right">{{ count($group->transactions) }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<div class="footer">
    <p>Generated by {{ auth()->user()?->username ?? config('app.name') }} on {{ now()->format('Y-m-d H:i:s') }}</p>
</div>
</body>
</html>
