<!DOCTYPE html>
<html>
<head>
    <title>Expense Report</title>
    <style>
        /* Same base styles as cash_flow.blade.php */
    </style>
    @include('partials.report-print-styles')
</head>
<body>
<div class="header">
    <h1>Expense Report</h1>
    <p>{{ $data->start_date }} to {{ $data->end_date }}</p>
    <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
</div>

@foreach($data->grouped_data as $groupName => $group)
    <h3>{{ $groupName }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Date</th>
            <th>Description</th>
            <th class="text-right">Amount</th>
            <th>Payment Method</th>
            <th>Recipient</th>
            <th>Approved By</th>
        </tr>
        </thead>
        <tbody>
        @foreach($group->expenditures as $expense)
            <tr>
                <td>{{ $expense->date->format('Y-m-d') }}</td>
                <td>{{ $expense->description }}</td>
                <td class="text-right">Tsh {{ number_format($expense->amount, 2) }}</td>
                <td>{{ ucfirst($expense->payment_method) }}</td>
                <td>{{ $expense->recipient_name }}</td>
                <td>{{ $expense->approvedBy->name ?? 'N/A' }}</td>
            </tr>
        @endforeach
        <tr>
            <td colspan="2"><strong>Total</strong></td>
            <td class="text-right"><strong>Tsh {{ number_format($group->total_amount, 2) }}</strong></td>
            <td colspan="3"></td>
        </tr>
        </tbody>
    </table>
@endforeach

<div class="footer">
    <p>Generated by {{ auth()->user()?->username ?? config('app.name') }} on {{ now()->format('Y-m-d H:i:s') }}</p>
</div>
</body>
</html>
