<!DOCTYPE html>
<html>
<head>
    <title>Income Report</title>
    <style>
        /* Same base styles as cash_flow.blade.php */
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        /* ... rest of the styles ... */
    </style>
    @include('partials.report-print-styles')
</head>
<body>
<div class="header">
    <h1>Income Report</h1>
    <p>{{ $data->start_date }} to {{ $data->end_date }}</p>
    <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
</div>

@foreach($data->grouped_data as $groupName => $group)
    <h3>{{ $groupName }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Date</th>
            <th>Description</th>
            <th class="text-right">Amount</th>
            <th>Payment Method</th>
            <th>Received By</th>
        </tr>
        </thead>
        <tbody>
        @foreach($group->incomes as $income)
            <tr>
                <td>{{ $income->date->format('Y-m-d') }}</td>
                <td>{{ $income->description }}</td>
                <td class="text-right">Tsh {{ number_format($income->amount, 2) }}</td>
                <td>{{ ucfirst($income->payment_method) }}</td>
                <td>{{ $income->receivedBy->name ?? 'N/A' }}</td>
            </tr>
        @endforeach
        <tr>
            <td colspan="2"><strong>Total</strong></td>
            <td class="text-right"><strong>Tsh {{ number_format($group->total_amount, 2) }}</strong></td>
            <td colspan="2"></td>
        </tr>
        </tbody>
    </table>
@endforeach

<div class="footer">
    <p>Generated by {{ auth()->user()?->username ?? config('app.name') }} on {{ now()->format('Y-m-d H:i:s') }}</p>
</div>
</body>
</html>
