<!DOCTYPE html>
<html>
<head>
    <title>Product Report</title>
    <style>
        /* Same base styles as cash_flow.blade.php */
    </style>
    @include('partials.report-print-styles')
</head>
<body>
<div class="header">
    <h1>Product Report</h1>
    <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
</div>

<h3>Inventory Summary</h3>
<table class="table">
    <thead>
    <tr>
        <th>Metric</th>
        <th class="text-right">Value</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Total Products</td>
        <td class="text-right">{{ $data->total_products }}</td>
    </tr>
    <tr>
        <td>Total Inventory Value</td>
        <td class="text-right">Tsh {{ number_format($data->total_stock_value, 2) }}</td>
    </tr>
    </tbody>
</table>

<h3>Products</h3>
<table class="table">
    <thead>
    <tr>
        <th>Product</th>
        <th>SKU</th>
        <th>Brand</th>
        <th class="text-right">Stock</th>
        <th class="text-right">Cost Price</th>
        <th class="text-right">Selling Price</th>
        <th class="text-right">Value</th>
    </tr>
    </thead>
    <tbody>
    @foreach($data->products as $product)
        <tr>
            <td>{{ $product->name }}</td>
            <td>{{ $product->sku }}</td>
            <td>{{ $product->brand->name ?? 'N/A' }}</td>
            <td class="text-right">{{ $product->quantity }}</td>
            <td class="text-right">Tsh {{ number_format($product->cost_price, 2) }}</td>
            <td class="text-right">Tsh {{ number_format($product->selling_price, 2) }}</td>
            <td class="text-right">Tsh {{ number_format($product->stock_value, 2) }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<div class="footer">
    <p>Generated by {{ auth()->user()?->username ?? config('app.name') }} on {{ now()->format('Y-m-d H:i:s') }}</p>
</div>
</body>
</html>
