<!DOCTYPE html>
<html>
<head>
    <title>Sales Report</title>
    <style>
        /* Same base styles as cash_flow.blade.php */
    </style>
    @include('partials.report-print-styles')
</head>
<body>
<div class="header">
    <h1>Sales Report</h1>
    <p>{{ $data->start_date }} to {{ $data->end_date }}</p>
    <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
</div>

@foreach($data->grouped_data as $groupName => $group)
    <h3>{{ $groupName }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Invoice #</th>
            <th>Date</th>
            <th>Customer</th>
            <th class="text-right">Amount</th>
            <th>Payment Method</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        @foreach($group->sales as $sale)
            <tr>
                <td>{{ $sale->invoice_number }}</td>
                <td>{{ $sale->completed_at->format('Y-m-d') }}</td>
                <td>{{ $sale->customer_name ?? 'Walk-in' }}</td>
                <td class="text-right">Tsh {{ number_format($sale->grand_total, 2) }}</td>
                <td>{{ ucfirst(str_replace('_', ' ', $sale->payment_method)) }}</td>
                <td>{{ ucfirst($sale->payment_status) }}</td>
            </tr>
        @endforeach
        <tr>
            <td colspan="3"><strong>Total</strong></td>
            <td class="text-right"><strong>Tsh {{ number_format($group->total_amount, 2) }}</strong></td>
            <td colspan="2"></td>
        </tr>
        <tr>
            <td colspan="3"><strong>Average Sale</strong></td>
            <td class="text-right"><strong>Tsh {{ number_format($group->average_sale, 2) }}</strong></td>
            <td colspan="2"></td>
        </tr>
        </tbody>
    </table>
@endforeach

<div class="footer">
    <p>Generated by {{ auth()->user()?->username ?? config('app.name') }} on {{ now()->format('Y-m-d H:i:s') }}</p>
</div>
</body>
</html>
