@extends('layouts.aviation')
@section('title','Fleet')
@section('content')
<div class="page-heading"><div><div class="eyebrow">Fleet management</div><h1>Aircraft</h1><p>Register airframes, credentials and base locations. Grounding periods are managed separately.</p></div><a class="av-btn av-btn-soft" href="{{ route('aviation.groundings.index') }}">Manage groundings</a></div>
@if(auth()->user()->hasPermission('aviation.manage'))<div class="av-card"><div class="av-card-head"><h2>Add aircraft</h2></div><div class="av-card-body"><form method="post" action="{{ route('aviation.aircraft.store') }}" class="av-form-grid">@csrf
<div><label>Registration</label><input required name="registration" class="form-control" value="{{ old('registration') }}" placeholder="5H-XXX"></div>
<div><label>Aircraft type</label><select required name="aircraft_type_id" class="form-select"><option value="">Select a type</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected(old('aircraft_type_id')==$type->id)>{{ $type->icao_designator }} · {{ $type->model }}</option>@endforeach</select></div>
<div><label>Home airport</label><select name="home_airport_id" class="form-select"><option value="">Choose airport</option>@foreach($airports as $airport)<option value="{{ $airport->id }}">{{ $airport->icao }} · {{ $airport->city }}</option>@endforeach</select></div>
<div><label>Serial number</label><input name="serial_number" class="form-control"></div>
<div><label>Airworthiness valid until</label><input type="date" name="airworthiness_expires_at" class="form-control"></div>
<div><label>Insurance valid until</label><input type="date" name="insurance_expires_at" class="form-control"></div>
<div><label>Status</label><select name="status" class="form-select"><option value="active">Active</option><option value="grounded">Grounded</option><option value="retired">Retired</option></select></div>
<div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save aircraft</button></div><div class="span4"><label>Notes</label><textarea name="notes" class="form-control" rows="2"></textarea></div>
</form></div></div>@endif
<div class="av-card"><div class="av-card-head"><h2>Fleet directory</h2><span class="av-sub">{{ $aircraft->total() }} aircraft</span></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>Registration</th><th>Type</th><th>Base</th><th>Airworthiness</th><th>Insurance</th><th>Status</th><th>Manage</th></tr></thead><tbody>
@forelse($aircraft as $plane)<tr><td><strong>{{ $plane->registration }}</strong><div class="av-sub">{{ $plane->serial_number }}</div></td><td>{{ $plane->type?->icao_designator }}</td><td>{{ $plane->homeAirport?->icao ?? '—' }}</td><td>{{ $plane->airworthiness_expires_at?->format('d M Y') ?? 'Missing' }}</td><td>{{ $plane->insurance_expires_at?->format('d M Y') ?? 'Missing' }}</td><td><span class="av-badge {{ $plane->status }}">{{ ucfirst($plane->status) }}</span></td><td>@if(auth()->user()->hasPermission('aviation.manage'))<details class="av-details"><summary>Edit details</summary><form method="post" action="{{ route('aviation.aircraft.update',$plane) }}" class="av-form-grid">@csrf @method('PUT')<div><label>Registration</label><input required name="registration" value="{{ $plane->registration }}" class="form-control"></div><div><label>Type</label><select required name="aircraft_type_id" class="form-select">@foreach($types as $type)<option value="{{ $type->id }}" @selected($plane->aircraft_type_id==$type->id)>{{ $type->icao_designator }} {{ $type->model }}</option>@endforeach</select></div><div><label>Home airport</label><select name="home_airport_id" class="form-select"><option value="">None</option>@foreach($airports as $airport)<option value="{{ $airport->id }}" @selected($plane->home_airport_id==$airport->id)>{{ $airport->icao }}</option>@endforeach</select></div><div><label>Serial number</label><input name="serial_number" value="{{ $plane->serial_number }}" class="form-control"></div><div><label>Airworthiness valid until</label><input type="date" name="airworthiness_expires_at" value="{{ $plane->airworthiness_expires_at?->format('Y-m-d') }}" class="form-control"></div><div><label>Insurance valid until</label><input type="date" name="insurance_expires_at" value="{{ $plane->insurance_expires_at?->format('Y-m-d') }}" class="form-control"></div><div><label>Status</label><select name="status" class="form-select">@foreach(['active','grounded','retired'] as $status)<option value="{{ $status }}" @selected($plane->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save</button></div><div class="span4"><label>Notes</label><textarea name="notes" class="form-control">{{ $plane->notes }}</textarea></div></form></details>@endif</td></tr>@empty<tr><td class="av-empty" colspan="7">Register aircraft and their type to start planning.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $aircraft->links('pagination::bootstrap-5') }}</div></div>
@endsection
