@extends('layouts.aviation')
@section('title','Airports')
@section('content')
<div class="page-heading"><div><div class="eyebrow">Reference data</div><h1>Airports</h1><p>Manage ICAO locations and their local time zones. Scheduling is entered and checked in UTC.</p></div></div>
@if(auth()->user()->hasPermission('aviation.manage'))<div class="av-card"><div class="av-card-head"><h2>Add airport</h2></div><div class="av-card-body"><form action="{{ route('aviation.airports.store') }}" method="post" class="av-form-grid">@csrf
@foreach(['icao'=>'ICAO code','iata'=>'IATA code','name'=>'Airport name','city'=>'City','country'=>'Country','timezone'=>'Time zone'] as $field=>$label)
@include('aviation.partials.airport-field',['value'=>old($field,'')])
@endforeach
<div><label for="active">Status</label><select name="active" id="active" class="form-select"><option value="1">Active</option><option value="0">Inactive</option></select></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save airport</button></div></form></div></div>@endif
<div class="av-card"><div class="av-card-head"><h2>Airport directory</h2><span class="av-sub">{{ $airports->total() }} locations</span></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>ICAO</th><th>Airport</th><th>Location</th><th>Time zone</th><th>Status</th><th>Manage</th></tr></thead><tbody>@forelse($airports as $airport)<tr><td><strong>{{ $airport->icao }}</strong><div class="av-sub">{{ $airport->iata }}</div></td><td>{{ $airport->name }}</td><td>{{ $airport->city }}, {{ $airport->country }}</td><td>{{ $airport->timezone }}</td><td><span class="av-badge {{ $airport->active?'active':'inactive' }}">{{ $airport->active?'Active':'Inactive' }}</span></td><td>@if(auth()->user()->hasPermission('aviation.manage'))<details class="av-details"><summary>Edit</summary><form action="{{ route('aviation.airports.update',$airport) }}" method="post" class="av-form-grid">@csrf @method('PUT')@foreach(['icao','iata','name','city','country','timezone'] as $field)
@include('aviation.partials.airport-field',['label'=>ucfirst($field),'value'=>$airport->{$field}])
@endforeach<div><label>Status</label><select class="form-select" name="active"><option value="1" @selected($airport->active)>Active</option><option value="0" @selected(!$airport->active)>Inactive</option></select></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save</button></div></form></details>@endif</td></tr>@empty<tr><td colspan="6" class="av-empty">Add your first airport to start planning flights.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $airports->links('pagination::bootstrap-5') }}</div></div>
@endsection
