@extends('layouts.aviation')
@section('title','Crew & ratings')
@section('content')
<div class="page-heading"><div><div class="eyebrow">People & qualifications</div><h1>Crew & ratings</h1><p>Link existing staff, record licence and medical validity, then add aircraft type qualifications for each roster role.</p></div><a class="av-btn av-btn-outline" href="{{ url('staffs') }}">Create staff record</a></div>
@if(auth()->user()->hasPermission('aviation.manage'))<div class="av-card"><div class="av-card-head"><h2>Add crew member</h2></div><div class="av-card-body"><form method="post" action="{{ route('aviation.crew.store') }}" class="av-form-grid">@csrf
<div><label>Staff member</label><select name="staff_id" class="form-select" required><option value="">Choose unlinked staff</option>@foreach($staff as $person)<option value="{{ $person->id }}">{{ $person->employee_number }} · {{ $person->first_name }} {{ $person->last_name }}</option>@endforeach</select></div>
<div><label>Crew category</label><select name="crew_category" class="form-select"><option value="pilot">Flight crew / pilot</option><option value="cabin">Cabin crew</option></select></div>
<div><label>Base airport</label><select name="base_airport_id" class="form-select"><option value="">No base</option>@foreach($airports as $airport)<option value="{{ $airport->id }}">{{ $airport->icao }}</option>@endforeach</select></div>
<div><label>Licence / certificate number</label><input name="licence_number" required class="form-control"></div>
<div><label>Licence / certificate expires</label><input type="date" name="licence_expires_at" required class="form-control"></div>
<div><label>Medical expires</label><input type="date" name="medical_expires_at" required class="form-control"></div>
<div><label>Status</label><select name="status" class="form-select"><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save crew</button></div>
<div class="span4"><label>Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div></form></div></div>@endif
<div class="av-card"><div class="av-card-head"><h2>Crew directory</h2><a href="{{ route('aviation.absences.index') }}" class="av-btn av-btn-soft">Absence calendar</a></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>Crew member</th><th>Category</th><th>Base</th><th>Credentials</th><th>Qualifications</th><th>Status</th><th>Manage</th></tr></thead><tbody>
@forelse($crew as $member)<tr><td><strong>{{ $member->staff?->first_name }} {{ $member->staff?->last_name }}</strong><div class="av-sub">{{ $member->staff?->employee_number }}</div></td><td>{{ ucfirst($member->crew_category) }}</td><td>{{ $member->baseAirport?->icao ?? '—' }}</td><td><div class="av-sub">{{ $member->licence_number }}</div>Licence {{ $member->licence_expires_at?->format('d M Y') }}<br>Medical {{ $member->medical_expires_at?->format('d M Y') }}</td><td>@forelse($member->qualifications as $q)<div class="av-sub">{{ $q->aircraftType?->icao_designator }} · {{ str_replace('_',' ',$q->role) }} · {{ $q->expires_at->format('d M Y') }}</div>@empty<span class="av-badge draft">No ratings</span>@endforelse</td><td><span class="av-badge {{ $member->status }}">{{ ucfirst($member->status) }}</span></td><td>@if(auth()->user()->hasPermission('aviation.manage'))<details class="av-details"><summary>Update / qualify</summary><form method="post" action="{{ route('aviation.crew.update',$member) }}" class="av-form-grid mb-3">@csrf @method('PUT')<input type="hidden" name="staff_id" value="{{ $member->staff_id }}"><input type="hidden" name="crew_category" value="{{ $member->crew_category }}"><div><label>Base airport</label><select name="base_airport_id" class="form-select"><option value="">None</option>@foreach($airports as $airport)<option value="{{ $airport->id }}" @selected($member->base_airport_id==$airport->id)>{{ $airport->icao }}</option>@endforeach</select></div><div><label>Licence number</label><input name="licence_number" class="form-control" value="{{ $member->licence_number }}" required></div><div><label>Licence expiry</label><input type="date" name="licence_expires_at" class="form-control" value="{{ $member->licence_expires_at->format('Y-m-d') }}" required></div><div><label>Medical expiry</label><input type="date" name="medical_expires_at" class="form-control" value="{{ $member->medical_expires_at->format('Y-m-d') }}" required></div><div><label>Status</label><select name="status" class="form-select"><option value="active" @selected($member->status==='active')>Active</option><option value="inactive" @selected($member->status==='inactive')>Inactive</option></select></div><div class="span2"><label>Notes</label><input name="notes" value="{{ $member->notes }}" class="form-control"></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Update profile</button></div></form>
<form method="post" action="{{ route('aviation.qualifications.store') }}" class="av-form-grid">@csrf<input type="hidden" name="crew_id" value="{{ $member->id }}"><div><label>Aircraft type</label><select name="aircraft_type_id" required class="form-select"><option value="">Choose type</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->icao_designator }}</option>@endforeach</select></div><div><label>Qualified role</label><select name="role" class="form-select">@if($member->crew_category==='pilot')<option value="captain">Captain / PIC</option><option value="first_officer">First officer / SIC</option>@else<option value="cabin_crew">Cabin crew</option>@endif</select></div><div><label>Certificate number</label><input name="certificate_number" class="form-control"></div><div><label>Qualification expiry</label><input type="date" name="expires_at" required class="form-control"></div><div class="span4"><button class="av-btn av-btn-soft">Add or renew qualification</button></div></form></details>@endif</td></tr>@empty<tr><td colspan="7" class="av-empty">Create a staff record, then attach a crew profile.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $crew->links('pagination::bootstrap-5') }}</div></div>
@endsection
