@extends('layouts.aviation')
@section('title','Operations overview')
@section('content')
<div class="page-heading"><div><div class="eyebrow">Flight operations</div><h1>Operations overview</h1><p>Fleet availability, upcoming legs, crew rosters and exceptions in one place.</p></div><a href="{{ route('aviation.flights.index') }}" class="av-btn av-btn-primary">Open schedule <i class="ti ti-arrow-right"></i></a></div>
<div class="av-card"><div class="av-card-body d-flex justify-content-between align-items-center flex-wrap gap-3"><div><strong>{{ $maintenanceDue }} maintenance check(s) due</strong><div class="av-sub">{{ $automaticLeave }} automatic pilot leave period(s) upcoming or in progress</div></div><a class="av-btn av-btn-outline" href="{{ route('aviation.automation.index') }}">View maintenance & pilot leave</a></div></div>

<div class="row g-3 mb-2">
    @foreach([['Active aircraft',$fleetCount,'ti-plane'],['Active crew',$crewCount,'ti-users'],['Next 7 days flights',$upcomingCount,'ti-calendar'],['Draft duties',$draftDuties,'ti-clipboard']] as [$label,$value,$icon])
    <div class="col-xl-3 col-sm-6"><div class="av-card av-stat"><i class="ti {{ $icon }}"></i><div class="label">{{ $label }}</div><div class="value">{{ number_format($value) }}</div><div class="av-sub">Current operations data</div></div></div>
    @endforeach
</div>
@if(!$approvedPolicies)<div class="av-alerts av-warning"><strong>Publication is paused.</strong> No approved fatigue policy is available. Enter operator-approved duty, FDP and rest limits in <a href="{{ route('aviation.policies.index') }}">Fatigue policies</a>.</div>@endif
@if(count($alerts))<div class="av-card"><div class="av-card-head"><h2>Published roster alerts</h2><span class="av-badge grounded">{{ count($alerts) }} duties to review</span></div><div class="av-card-body">@foreach($alerts as $alert)<div class="av-alerts av-warning"><strong>{{ $alert['reference'] }}</strong><ul>@foreach($alert['issues'] as $issue)<li>{{ $issue }}</li>@endforeach</ul></div>@endforeach</div></div>@endif
<div class="row g-3"><div class="col-xl-8"><div class="av-card"><div class="av-card-head"><h2>Upcoming flights</h2><a href="{{ route('aviation.flights.index') }}" class="av-btn av-btn-soft">All flights</a></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>Flight</th><th>Route</th><th>Departure UTC</th><th>Aircraft</th><th>Roster</th></tr></thead><tbody>
@forelse($upcoming as $flight)<tr><td><strong>{{ $flight->flight_number }}</strong><div class="av-sub">{{ $flight->status }}</div></td><td>{{ $flight->origin?->icao }} → {{ $flight->destination?->icao }}</td><td>{{ $flight->departure_at->format('d M, H:i') }}</td><td>{{ $flight->aircraft?->registration }}</td><td><span class="av-badge {{ $flight->duty?->status==='published'?'published':'draft' }}">{{ $flight->duty?->status ?? 'Unassigned' }}</span></td></tr>@empty<tr><td colspan="5" class="av-empty">No flights in the next seven days.</td></tr>@endforelse
</tbody></table></div></div></div><div class="col-xl-4"><div class="av-card"><div class="av-card-head"><h2>Latest safety events</h2><a href="{{ route('aviation.events.index') }}" class="av-btn av-btn-soft">View log</a></div><div class="av-card-body"><ul class="av-list">@forelse($recentEvents as $event)<li><strong>{{ str_replace('_',' ',ucfirst($event->event_type)) }}</strong><div class="av-sub">{{ $event->created_at->format('d M Y H:i') }} UTC · {{ count($event->issues) }} issue(s)</div></li>@empty<li class="av-sub">No safety events recorded.</li>@endforelse</ul></div></div><div class="av-help">The supplied FRM page lists flight time ceilings. Approved FDP and rest values must come from your complete operator manual before crew duties can be published.</div></div></div>
@endsection
