@extends('layouts.aviation')
@section('title','Crew duty roster')
@section('content')
<div class="page-heading"><div><div class="eyebrow">Crew planning</div><h1>Crew duty roster</h1><p>Build flight, standby, positioning and other duties. Publish only after document, rest, qualification and cumulative-limit checks pass.</p></div><a class="av-btn av-btn-outline" href="{{ route('aviation.policies.index') }}">Review policies</a></div>
<div class="av-card"><div class="av-card-body"><form method="get" class="av-filter"><div><label>From UTC</label><input class="form-control" type="date" name="from" value="{{ $from }}"></div><div><label>Until UTC</label><input class="form-control" type="date" name="to" value="{{ $to }}"></div><button class="av-btn av-btn-primary">Filter duties</button></form></div></div>
@if(auth()->user()->hasPermission('aviation.manage'))<div class="av-card"><div class="av-card-head"><h2>Create duty draft</h2><span class="av-sub">Report and release are always UTC</span></div><div class="av-card-body"><form method="post" action="{{ route('aviation.duties.store') }}" class="av-form-grid">@csrf
<div><label>Duty reference</label><input name="reference" value="{{ old('reference') }}" class="form-control" required placeholder="DUTY-2026-001"></div>
<div><label>Duty type</label><select name="type" class="form-select">@foreach(['flight','standby','positioning','deadheading','training','split_duty','other'] as $type)<option value="{{ $type }}">{{ ucfirst(str_replace('_',' ',$type)) }}</option>@endforeach</select></div>
<div><label>Report at UTC</label><input type="datetime-local" name="report_at" value="{{ old('report_at') }}" class="form-control" required></div><div><label>Release at UTC</label><input type="datetime-local" name="release_at" value="{{ old('release_at') }}" class="form-control" required></div>
<div><label>Flight crew policy</label><select name="pilot_policy_id" class="form-select"><option value="">Select approved policy</option>@foreach($policies->where('crew_category','pilot') as $policy)<option value="{{ $policy->id }}">{{ $policy->name }} (#{{ $policy->id }})</option>@endforeach</select></div>
<div><label>Cabin crew policy</label><select name="cabin_policy_id" class="form-select"><option value="">Select if cabin crew is rostered</option>@foreach($policies->where('crew_category','cabin') as $policy)<option value="{{ $policy->id }}">{{ $policy->name }} (#{{ $policy->id }})</option>@endforeach</select></div>
<div class="span2"><label>Notes</label><input name="notes" value="{{ old('notes') }}" class="form-control"></div><div class="span4"><button class="av-btn av-btn-primary">Create duty</button></div></form></div></div>@endif
<div class="av-help mb-3">Drafts may be incomplete. Publishing requires an approved policy for each crew category, one captain on flight duties, aircraft-specific qualified crew, usable rest, and a conflict-free flight schedule. Recording standby or split duty does not automatically extend a policy limit.</div>
<div class="av-card"><div class="av-card-head"><h2>Duty board</h2><span class="av-sub">{{ $duties->total() }} duties in selected period</span></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>Reference</th><th>Reporting → release UTC</th><th>Crew</th><th>Flights / activities</th><th>Status</th><th>Workflow</th></tr></thead><tbody>
@forelse($duties as $duty)<tr><td><strong>{{ $duty->reference }}</strong><div class="av-sub">{{ ucfirst(str_replace('_',' ',$duty->type)) }}</div></td><td>{{ $duty->report_at->format('d M H:i') }} → {{ $duty->release_at->format('d M H:i') }}<div class="av-sub">{{ $duty->report_at->diffInMinutes($duty->release_at) }} minutes</div></td><td>{{ $duty->crew->count() }} assigned<div class="av-sub">@foreach($duty->crew as $person){{ $person->staff?->first_name }} ({{ str_replace('_',' ',$person->pivot->role) }}){{ !$loop->last?', ':'' }}@endforeach</div></td><td>{{ $duty->flights->count() }} flight legs<div class="av-sub">{{ $duty->activities->count() }} other activities</div></td><td><span class="av-badge {{ $duty->status }}">{{ ucfirst($duty->status) }}</span></td><td><div class="av-actions">@if(auth()->user()->hasPermission('aviation.publish'))
@if($duty->status==='draft')<form action="{{ route('aviation.duties.publish',$duty) }}" method="post">@csrf<button class="av-btn av-btn-primary" title="Run full safety checks">Publish roster</button></form>
@elseif($duty->status==='published')<form action="{{ route('aviation.duties.unpublish',$duty) }}" method="post">@csrf<button class="av-btn av-btn-outline">Unpublish</button></form>@endif
@endif</div><details class="av-details"><summary>Duty details</summary><div class="av-sub mb-2">Pilot policy: {{ $duty->pilotPolicy?->name ?? 'Unset' }} · Cabin policy: {{ $duty->cabinPolicy?->name ?? 'Unset' }}</div>
@if($duty->status==='draft' && auth()->user()->hasPermission('aviation.manage'))
<form action="{{ route('aviation.duties.update',$duty) }}" method="post" class="av-form-grid mb-3">@csrf @method('PUT')<div><label>Reference</label><input name="reference" value="{{ $duty->reference }}" class="form-control" required></div><div><label>Type</label><select name="type" class="form-select">@foreach(['flight','standby','positioning','deadheading','training','split_duty','other'] as $type)<option value="{{ $type }}" @selected($duty->type===$type)>{{ ucfirst(str_replace('_',' ',$type)) }}</option>@endforeach</select></div><div><label>Report UTC</label><input type="datetime-local" name="report_at" value="{{ $duty->report_at->format('Y-m-d\TH:i') }}" class="form-control" required></div><div><label>Release UTC</label><input type="datetime-local" name="release_at" value="{{ $duty->release_at->format('Y-m-d\TH:i') }}" class="form-control" required></div><div><label>Pilot policy</label><select name="pilot_policy_id" class="form-select"><option value="">Unset</option>@foreach($policies->where('crew_category','pilot') as $policy)<option value="{{ $policy->id }}" @selected($duty->pilot_policy_id==$policy->id)>{{ $policy->name }}</option>@endforeach</select></div><div><label>Cabin policy</label><select name="cabin_policy_id" class="form-select"><option value="">Unset</option>@foreach($policies->where('crew_category','cabin') as $policy)<option value="{{ $policy->id }}" @selected($duty->cabin_policy_id==$policy->id)>{{ $policy->name }}</option>@endforeach</select></div><div class="span2"><label>Notes</label><input name="notes" value="{{ $duty->notes }}" class="form-control"></div><div class="span4"><button class="av-btn av-btn-soft">Update duty</button></div></form>
<div class="row g-3"><div class="col-xl-6"><div class="av-help"><strong>Assigned crew</strong><div class="av-sub mb-2">@foreach($duty->crew as $person)<span>{{ $person->staff?->first_name }} {{ $person->staff?->last_name }} ({{ $person->pivot->role }})</span> @endforeach</div><form method="post" action="{{ route('aviation.duties.assign',$duty) }}" class="av-filter">@csrf<select name="crew_id" class="form-select" required><option value="">Crew member</option>@foreach($crew as $person)<option data-crew-category="{{ $person->crew_category }}" value="{{ $person->id }}">{{ $person->staff?->first_name }} {{ $person->staff?->last_name }} · {{ $person->crew_category }}</option>@endforeach</select><select name="role" class="form-select"><option value="captain">Captain</option><option value="first_officer">First officer</option><option value="cabin_crew">Cabin crew</option></select><button class="av-btn av-btn-primary">Assign</button></form>@foreach($duty->crew as $person)<form class="d-inline-block mt-2 me-1" method="post" action="{{ route('aviation.duties.crew.destroy',[$duty,$person]) }}">@csrf @method('DELETE')<button class="av-btn av-btn-danger">Remove {{ $person->staff?->first_name }}</button></form>@endforeach</div></div>
<div class="col-xl-6"><div class="av-help"><strong>Flight legs</strong><div class="av-sub mb-2">@foreach($duty->flights as $leg){{ $leg->flight_number }} {{ $leg->origin?->icao }}–{{ $leg->destination?->icao }}{{ !$loop->last?', ':'' }}@endforeach</div><form method="post" action="{{ route('aviation.duties.flights.store',$duty) }}" class="av-filter">@csrf<select name="flight_id" required class="form-select"><option value="">Select unassigned flight</option>@foreach($flights->whereNull('duty_id') as $leg)<option value="{{ $leg->id }}">{{ $leg->flight_number }} · {{ $leg->departure_at->format('d M H:i') }}</option>@endforeach</select><button class="av-btn av-btn-primary">Add leg</button></form>@foreach($duty->flights as $leg)<form method="post" action="{{ route('aviation.duties.flights.destroy',[$duty,$leg]) }}" class="d-inline-block mt-2 me-1">@csrf @method('DELETE')<button class="av-btn av-btn-danger">Detach {{ $leg->flight_number }}</button></form>@endforeach</div></div></div>
<div class="av-help mt-3"><strong>Other duty activities</strong><div class="av-sub">@foreach($duty->activities as $activity){{ str_replace('_',' ',$activity->type) }} {{ $activity->starts_at->format('H:i') }}–{{ $activity->ends_at->format('H:i') }}; @endforeach</div><form method="post" action="{{ route('aviation.duties.activities.store',$duty) }}" class="av-filter mt-2">@csrf<select name="type" class="form-select">@foreach(['standby','positioning','deadheading','split_duty','training','preflight','postflight','other'] as $type)<option value="{{ $type }}">{{ ucwords(str_replace('_',' ',$type)) }}</option>@endforeach</select><div><label>Start UTC</label><input type="datetime-local" name="starts_at" required class="form-control"></div><div><label>End UTC</label><input type="datetime-local" name="ends_at" required class="form-control"></div><input name="notes" class="form-control" placeholder="Description"><button class="av-btn av-btn-soft">Add activity</button></form></div>
@elseif($duty->status==='published' && auth()->user()->hasPermission('aviation.publish'))<div class="av-help">Record actual times on each flight, then close this duty.</div><form class="av-form-grid mt-2" method="post" action="{{ route('aviation.duties.complete',$duty) }}">@csrf<div><label>Actual report UTC</label><input type="datetime-local" name="actual_report_at" class="form-control" value="{{ $duty->actual_report_at?->format('Y-m-d\TH:i') }}" required></div><div><label>Actual release UTC</label><input type="datetime-local" name="actual_release_at" class="form-control" value="{{ $duty->actual_release_at?->format('Y-m-d\TH:i') }}" required></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Complete & check</button></div></form>
@else<div class="av-sub">Actual report: {{ $duty->actual_report_at?->format('d M H:i') ?? '—' }} · Actual release: {{ $duty->actual_release_at?->format('d M H:i') ?? '—' }}</div>@endif
</details></td></tr>
@empty<tr><td colspan="6" class="av-empty">No duties in this date range. Create a draft, assign crew and attach flights.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $duties->links('pagination::bootstrap-5') }}</div></div>
@endsection
