@extends('layouts.aviation')
@section('title','Flight schedule')
@section('content')
<div class="page-heading"><div><div class="eyebrow">Aircraft planning</div><h1>Flight schedule</h1><p>Plan UTC flight legs, check aircraft availability and record actual off/on block times.</p></div><a href="{{ route('aviation.duties.index') }}" class="av-btn av-btn-outline">Crew duty roster</a></div>
<div class="av-card"><div class="av-card-body"><form method="get" class="av-filter"><div><label>From date UTC</label><input type="date" class="form-control" name="from" value="{{ $from }}"></div><div><label>To date UTC</label><input type="date" class="form-control" name="to" value="{{ $to }}"></div><div><label>Aircraft</label><select name="aircraft_id" class="form-select"><option value="">All aircraft</option>@foreach($aircraft as $plane)<option value="{{ $plane->id }}" @selected(request('aircraft_id')==$plane->id)>{{ $plane->registration }}</option>@endforeach</select></div><button class="av-btn av-btn-primary" type="submit">Apply filters</button></form></div></div>
@if(auth()->user()->hasPermission('aviation.manage'))<div class="av-card"><div class="av-card-head"><h2>Draft a flight leg</h2><span class="av-sub">Enter all time fields in UTC</span></div><div class="av-card-body"><form method="post" action="{{ route('aviation.flights.store') }}" class="av-form-grid">@csrf
<div><label>Flight number</label><input name="flight_number" class="form-control" value="{{ old('flight_number') }}" required placeholder="AH101"></div>
<div><label>Leg sequence</label><input type="number" min="1" max="99" name="leg_sequence" value="{{ old('leg_sequence',1) }}" class="form-control" required></div>
<div><label>Aircraft</label><select name="aircraft_id" class="form-select" required><option value="">Select registration</option>@foreach($aircraft as $plane)<option value="{{ $plane->id }}" @selected(old('aircraft_id')==$plane->id)>{{ $plane->registration }} · {{ $plane->type?->icao_designator }}</option>@endforeach</select></div>
<div><label>Departure airport</label><select name="origin_id" class="form-select" required><option value="">Origin</option>@foreach($airports as $airport)<option value="{{ $airport->id }}" @selected(old('origin_id')==$airport->id)>{{ $airport->icao }} · {{ $airport->city }}</option>@endforeach</select></div>
<div><label>Arrival airport</label><select name="destination_id" class="form-select" required><option value="">Destination</option>@foreach($airports as $airport)<option value="{{ $airport->id }}" @selected(old('destination_id')==$airport->id)>{{ $airport->icao }} · {{ $airport->city }}</option>@endforeach</select></div>
<div><label>Scheduled departure UTC</label><input type="datetime-local" class="form-control" name="departure_at" value="{{ old('departure_at') }}" required></div><div><label>Scheduled arrival UTC</label><input type="datetime-local" class="form-control" name="arrival_at" value="{{ old('arrival_at') }}" required></div>
<div><label>Planned landings</label><input type="number" min="1" max="20" name="planned_landings" value="{{ old('planned_landings',1) }}" class="form-control" required></div><div><label>Attach to draft flight duty (optional)</label><select name="duty_id" class="form-select"><option value="">Attach later</option>@foreach($duties as $duty)<option value="{{ $duty->id }}" @selected(old('duty_id')==$duty->id)>{{ $duty->reference }}</option>@endforeach</select></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save draft flight</button></div><div class="span4"><label>Notes</label><input name="notes" value="{{ old('notes') }}" class="form-control"></div></form></div></div>@endif
<div class="av-card"><div class="av-card-head"><h2>Flight legs</h2><span class="av-sub">{{ $flights->total() }} for selected dates</span></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>Flight</th><th>Sector</th><th>Scheduled UTC</th><th>Aircraft</th><th>Duty / crew</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($flights as $flight)<tr><td><strong>{{ $flight->flight_number }}</strong><div class="av-sub">Leg {{ $flight->leg_sequence }} · {{ $flight->flight_date->format('d M Y') }}</div></td><td><strong>{{ $flight->origin?->icao }} → {{ $flight->destination?->icao }}</strong></td><td>{{ $flight->departure_at->format('d M H:i') }} → {{ $flight->arrival_at->format('d M H:i') }}<div class="av-sub">{{ $flight->departure_at->diffInMinutes($flight->arrival_at) }} min planned</div></td><td>{{ $flight->aircraft?->registration }}</td><td>{{ $flight->duty?->reference ?? 'Not assigned' }}<div class="av-sub">{{ $flight->duty?->status ?? 'No crew roster' }}</div></td><td><span class="av-badge {{ $flight->status }}">{{ ucfirst($flight->status) }}</span></td><td>
@if(auth()->user()->hasPermission('aviation.publish'))<div class="av-actions">@if($flight->status==='draft')<form method="post" action="{{ route('aviation.flights.schedule',$flight) }}">@csrf<button class="av-btn av-btn-soft">Schedule</button></form>@elseif($flight->status==='scheduled' && $flight->duty?->status!=='published')<form method="post" action="{{ route('aviation.flights.unschedule',$flight) }}">@csrf<button class="av-btn av-btn-outline">Unschedule</button></form>@endif</div>@endif
@if($flight->status==='scheduled' && $flight->duty?->status==='published' && auth()->user()->hasPermission('aviation.publish'))<details class="av-details"><summary>Record actual block</summary><form method="post" action="{{ route('aviation.flights.actual',$flight) }}" class="av-form-grid">@csrf<div><label>Off-block UTC</label><input type="datetime-local" name="actual_off_at" class="form-control" required value="{{ $flight->actual_off_at?->format('Y-m-d\TH:i') }}"></div><div><label>On-block UTC</label><input type="datetime-local" name="actual_on_at" class="form-control" required value="{{ $flight->actual_on_at?->format('Y-m-d\TH:i') }}"></div><div><label>Actual landings</label><input type="number" min="1" max="20" name="actual_landings" value="{{ $flight->actual_landings ?? $flight->planned_landings }}" class="form-control" required></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save actual</button></div></form></details>@endif
@if($flight->status==='draft' && auth()->user()->hasPermission('aviation.manage'))<details class="av-details"><summary>Edit draft</summary><form method="post" action="{{ route('aviation.flights.update',$flight) }}" class="av-form-grid">@csrf @method('PUT')<div><label>Flight number</label><input name="flight_number" value="{{ $flight->flight_number }}" class="form-control" required></div><div><label>Leg sequence</label><input type="number" min="1" max="99" name="leg_sequence" value="{{ $flight->leg_sequence }}" class="form-control" required></div><div><label>Aircraft</label><select name="aircraft_id" class="form-select" required>@foreach($aircraft as $plane)<option value="{{ $plane->id }}" @selected($flight->aircraft_id==$plane->id)>{{ $plane->registration }}</option>@endforeach</select></div><div><label>Origin</label><select name="origin_id" class="form-select" required>@foreach($airports as $airport)<option value="{{ $airport->id }}" @selected($flight->origin_id==$airport->id)>{{ $airport->icao }}</option>@endforeach</select></div><div><label>Destination</label><select name="destination_id" class="form-select" required>@foreach($airports as $airport)<option value="{{ $airport->id }}" @selected($flight->destination_id==$airport->id)>{{ $airport->icao }}</option>@endforeach</select></div><div><label>Departure UTC</label><input name="departure_at" type="datetime-local" class="form-control" value="{{ $flight->departure_at->format('Y-m-d\TH:i') }}" required></div><div><label>Arrival UTC</label><input name="arrival_at" type="datetime-local" class="form-control" value="{{ $flight->arrival_at->format('Y-m-d\TH:i') }}" required></div><div><label>Planned landings</label><input type="number" min="1" max="20" name="planned_landings" value="{{ $flight->planned_landings }}" class="form-control" required></div><div><label>Draft flight duty</label><select name="duty_id" class="form-select"><option value="">None</option>@foreach($duties as $duty)<option value="{{ $duty->id }}" @selected($flight->duty_id==$duty->id)>{{ $duty->reference }}</option>@endforeach</select></div><div class="d-flex align-items-end"><button class="av-btn av-btn-primary">Save draft</button></div><div class="span4"><label>Notes</label><input name="notes" class="form-control" value="{{ $flight->notes }}"></div></form></details>@endif
</td></tr>@empty<tr><td colspan="7" class="av-empty">No flight legs in this period. Adjust the filters or draft a new leg.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $flights->links('pagination::bootstrap-5') }}</div></div>
@endsection
