@extends('layouts.aviation')
@section('title','My roster')
@section('content')
<div class="page-heading"><div><div class="eyebrow">Crew workspace</div><h1>My duty roster</h1><p>Your assigned published duties and flights, shown in UTC. Report fatigue or inability to operate as soon as you know.</p></div></div>
@if(!$crew)<div class="av-alerts av-warning">Your account is not linked to a crew profile. Ask the operations administrator to link your staff record and qualifications.</div>
@else
<div class="av-card"><div class="av-card-head"><h2>{{ $crew->staff?->first_name }} {{ $crew->staff?->last_name }}</h2><span class="av-badge {{ $crew->status }}">{{ ucfirst($crew->crew_category) }} · {{ ucfirst($crew->status) }}</span></div><div class="av-card-body av-sub">Licence/certificate valid to {{ $crew->licence_expires_at?->format('d M Y') }} · Medical valid to {{ $crew->medical_expires_at?->format('d M Y') }} · All times UTC</div></div>
<div class="av-card"><div class="av-card-head"><h2>Upcoming and recent duties</h2></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>Duty / status</th><th>Report UTC</th><th>Release UTC</th><th>Your role</th><th>Flights</th></tr></thead><tbody>@forelse($duties as $duty)<tr><td><strong>{{ $duty->reference }}</strong><div class="av-sub">{{ ucfirst(str_replace('_',' ',$duty->type)) }} · {{ $duty->status }}</div></td><td>{{ $duty->report_at->format('d M Y H:i') }}</td><td>{{ $duty->release_at->format('d M Y H:i') }}</td><td>{{ str_replace('_',' ',ucfirst($duty->pivot->role)) }}</td><td>@forelse($duty->flights as $flight)<div>{{ $flight->flight_number }} · {{ $flight->origin?->icao }} → {{ $flight->destination?->icao }} · {{ $flight->departure_at->format('d M H:i') }}</div>@empty<span class="av-sub">No flights ({{ $duty->type }} duty)</span>@endforelse</td></tr>@empty<tr><td class="av-empty" colspan="5">No published duties in the current roster window.</td></tr>@endforelse</tbody></table></div></div>
<div class="av-card"><div class="av-card-head"><h2>Report fatigue or unfitness</h2></div><div class="av-card-body"><p class="av-sub">Reports are retained in the safety event log. Marking yourself unfit creates an unavailable period that prevents future rostering; an existing published duty is flagged for operations review.</p><form method="post" action="{{ route('aviation.my-roster.report') }}" class="av-form-grid">@csrf<div class="span2"><label>Related duty (optional)</label><select name="duty_id" class="form-select"><option value="">General fatigue report</option>@foreach($duties as $duty)<option value="{{ $duty->id }}">{{ $duty->reference }} · {{ $duty->report_at->format('d M Y') }}</option>@endforeach</select></div><div class="span2"><label>Unable to operate?</label><select name="unfit_for_duty" class="form-select"><option value="0">No, reporting a concern</option><option value="1">Yes, mark me unavailable</option></select></div><div class="span2"><label>Unavailable until (UTC, required if unfit)</label><input type="datetime-local" name="unfit_until" class="form-control"></div><div class="span4"><label>What happened and what support is needed?</label><textarea name="details" required minlength="20" rows="4" class="form-control" placeholder="Describe the fatigue concern or reason you cannot operate."></textarea></div><div class="span4"><button class="av-btn av-btn-primary">Submit confidential operations report</button></div></form></div></div>
@endif
@endsection
