@extends('layouts.aviation')
@section('title','Fatigue policies')
@section('content')
@php($labels=['max_flight_24h_single_minutes'=>'Flight time · any 24h · single pilot','max_flight_24h_multi_minutes'=>'Flight time · any 24h · two pilots','max_flight_7d_minutes'=>'Flight time · any 7 days','max_flight_28d_minutes'=>'Flight time · any 28 days','max_flight_12mo_minutes'=>'Flight time · any 12 calendar months','max_fdp_minutes'=>'Flight duty period · max','max_duty_minutes'=>'Total duty period · max','max_duty_7d_minutes'=>'Duty time · any 7 days','max_duty_28d_minutes'=>'Duty time · any 28 days','max_duty_12mo_minutes'=>'Duty time · any 12 calendar months','min_rest_minutes'=>'Rest between duties · min','max_sectors_per_duty'=>'Sectors per duty · max','max_landings_per_duty'=>'Landings per duty · max'])
<div class="page-heading"><div><div class="eyebrow">Safety configuration</div><h1>Fatigue policies</h1><p>Numbers are stored per approved policy with effective dates and source. A published roster always checks its assigned policy.</p></div></div>
<div class="av-help mb-3">The attached AH Airways manual, page 29, provides pilot flight-time limits only: 480 minutes per 24 hours, 2,040 per 7 days, 6,000 per 28 days and 60,000 per 12 calendar months. Enter approved FDP, duty, sector, rest and cabin values from the full manual. A policy cannot be approved with these values blank.</div>
@if(auth()->user()->hasPermission('aviation.policy'))<div class="av-card"><div class="av-card-head"><h2>Create policy draft</h2></div><div class="av-card-body"><form method="post" action="{{ route('aviation.policies.store') }}" class="av-form-grid">@csrf
<div class="span2"><label>Policy name</label><input name="name" required class="form-control" value="{{ old('name') }}"></div><div><label>Crew category</label><select name="crew_category" class="form-select"><option value="pilot">Flight crew</option><option value="cabin">Cabin crew</option></select></div><div><label>Source / manual reference</label><input name="source_reference" required class="form-control"></div><div><label>Effective from</label><input name="effective_from" type="date" class="form-control"></div><div><label>Effective until</label><input name="effective_until" type="date" class="form-control"></div><div class="span2"><label>Notes</label><input name="notes" class="form-control"></div>
@foreach($labels as $field=>$label)<div><label>{{ $label }} {{ in_array($field,['max_sectors_per_duty','max_landings_per_duty'])?'(count)':'(minutes)' }}</label><input type="number" min="1" name="{{ $field }}" value="{{ old($field) }}" class="form-control"></div>@endforeach
<div class="span4"><button class="av-btn av-btn-primary">Save draft</button></div></form></div></div>@endif
<div class="av-card"><div class="av-card-head"><h2>Policy register</h2><span class="av-sub">{{ $policies->total() }} policies</span></div><div class="px-3 py-2"><button type="button" class="av-btn av-btn-outline" data-refresh-table>Refresh table</button></div><div class="table-responsive"><table class="table av-table"><thead><tr><th>Policy / source</th><th>Category</th><th>Valid period</th><th>Flight 24h / 7d / 28d / 12mo</th><th>Duty / FDP / rest</th><th>Status</th><th>Details</th></tr></thead><tbody>@forelse($policies as $policy)
<tr><td><strong>{{ $policy->name }}</strong><div class="av-sub">{{ $policy->source_reference }}</div></td><td>{{ ucfirst($policy->crew_category) }}</td><td>{{ $policy->effective_from?->format('d M Y') ?? 'Unset' }} → {{ $policy->effective_until?->format('d M Y') ?? 'Unset' }}</td><td><div class="av-sub">{{ $policy->max_flight_24h_single_minutes ?? '—' }} / {{ $policy->max_flight_7d_minutes ?? '—' }} / {{ $policy->max_flight_28d_minutes ?? '—' }} / {{ $policy->max_flight_12mo_minutes ?? '—' }} min</div></td><td>{{ $policy->max_duty_minutes ?? '—' }} / {{ $policy->max_fdp_minutes ?? '—' }} / {{ $policy->min_rest_minutes ?? '—' }} min</td><td><span class="av-badge {{ $policy->status }}">{{ ucfirst($policy->status) }}</span></td><td><details class="av-details"><summary>{{ $policy->status==='draft'?'Complete policy':'View limits' }}</summary><div class="av-sub mb-3">{{ $policy->notes }}</div>
@if($policy->status==='draft' && auth()->user()->hasPermission('aviation.policy'))<form action="{{ route('aviation.policies.update',$policy) }}" method="post" class="av-form-grid">@csrf @method('PUT')<div class="span2"><label>Name</label><input name="name" class="form-control" value="{{ $policy->name }}" required></div><div><label>Category</label><select name="crew_category" class="form-select"><option value="pilot" @selected($policy->crew_category==='pilot')>Flight crew</option><option value="cabin" @selected($policy->crew_category==='cabin')>Cabin crew</option></select></div><div><label>Source reference</label><input name="source_reference" class="form-control" value="{{ $policy->source_reference }}" required></div><div><label>Effective from</label><input type="date" name="effective_from" value="{{ $policy->effective_from?->format('Y-m-d') }}" class="form-control"></div><div><label>Effective until</label><input type="date" name="effective_until" value="{{ $policy->effective_until?->format('Y-m-d') }}" class="form-control"></div><div class="span2"><label>Notes</label><input name="notes" value="{{ $policy->notes }}" class="form-control"></div>
@foreach($labels as $field=>$label)<div><label>{{ $label }} {{ in_array($field,['max_sectors_per_duty','max_landings_per_duty'])?'(count)':'(minutes)' }}</label><input type="number" min="1" name="{{ $field }}" value="{{ $policy->{$field} }}" class="form-control"></div>@endforeach<div class="span4"><button class="av-btn av-btn-primary">Save values</button></div></form><form method="post" action="{{ route('aviation.policies.approve',$policy) }}" class="mt-3">@csrf<button class="av-btn av-btn-warn" onclick="return confirm('Confirm every value and its source against the approved operator manual?')">Approve completed policy</button></form>
@else<div class="av-form-grid">@foreach($labels as $field=>$label)<div class="av-sub"><strong>{{ $label }}</strong><br>{{ $policy->{$field} ?? '—' }}</div>@endforeach</div>@endif</details></td></tr>
@empty<tr><td colspan="7" class="av-empty">No fatigue policies yet.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $policies->links('pagination::bootstrap-5') }}</div></div>
@endsection
